### ISSUE TITLE
position issue for grouped objects

### ISSUE THREAD

**Issue by ghost** [TitusLVR/BMAX_Connector#1]
[https://ibb.co/895Ddvp](url)

objects that are grouped in 3ds max 2020 come into blender 2.8 with incorrect z axis position.
It seems they are all too high. This does not affect all groups.

**Comment by ghost** [comment]
another example of position issue. This object is showing inverse scale values. -1,-1,-1
This will be a result of being flipped in 3ds max I guess
[https://ibb.co/180VybL](url)

**Comment by TitusLVR** [comment]
It's a 3dsmax problem, and should be fixed manually.
