### ISSUE TITLE
Color Correction node not supported

### ISSUE THREAD

**Issue by ghost** [TitusLVR/BMAX_Connector#2]
It seems that the 3ds max color correction node in 3ds max 2020 does not transfer the texture to Blender. Could you read the texture file in the color correction node (3ds max) and just transfer that as an image file to Blender? I wouldn't mind losing the effect of the color correction node in exchange for having the texture in Blender.

**Comment by TitusLVR** [comment]
FBX limited. Required an extra material exporter.
