### ISSUE TITLE
Drag and Drop Not working 3ds Max 2018 and 2020

### ISSUE THREAD

**Issue by SparkingWater-GMAI** [TitusLVR/BMAX_Connector#6]
Dragging and Dropping is not working no icons appear. if you try to run the script from within 3ds max you get an error as well or drag the script into max.
![BlenderMAX](https://user-images.githubusercontent.com/18606317/80294258-821d1700-871c-11ea-9e2e-da60a4b37e86.PNG)

**Comment by Stephanvs** [comment]
It also doesn't seem to work on Max 2021.

When I drag/drop the .mzp file from Windows Explorer onto the 3ds Max Viewport, nothing seems to happen, no message, no warning.

This is the error I get when choosing `Scripting > Run script...` and then opening the .mzp file. (version 1.14)
![image](https://user-images.githubusercontent.com/375631/104597831-1dbd3180-5676-11eb-9f1b-6671d8bb6a84.png)
