### ISSUE TITLE
Perfect, but I missing important export function

### ISSUE THREAD

**Issue by remark3d** [TitusLVR/BMAX_Connector#9]
Hello

Your plugin is perfect, but would it be possible to implement the following?

I always need to export FBX from Blender to 3ds max even with textures/bitmaps.
So when exporting FBX I need to "turn on" the function - Path Mode: Copy + Embed Textures

Or is this already implemented but I'm doing something wrong?

Regards
Martin

**Comment by Furash** [comment]
You can change export parameters in these lines in BMAX_Connector/functions/FBX_export.py
From:
path_mode='AUTO', 
embed_textures=False, 
To:
path_mode='COPY', 
embed_textures=True, 

Check this to get a better idea https://docs.blender.org/api/current/bpy.ops.export_scene.html

**Comment by remark3d** [comment]
Wow, thank you 

and sorry for disturb, I must more read docs :-)

Kind regards
Martin
